name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: ubuntu-22.04
          platform: linux
        - os: macos-latest
          platform: macos
          preset: release-macos
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup
      run: |
        ci/${{ matrix.platform }}/setup.sh
    - name: Configure
      run: |
        cmake --preset ${{ matrix.preset || 'release' }}
    - name: Build
      run: |
        cmake --build --preset release
